--- !com.fakerest.bean.Route
method: get
url: /path1
defaultAnswer: !com.fakerest.bean.Answer
  status: 200
  body: response text
  headers:
    header22: value22
    Content-Type: text/html
  removeCookies:
    # [cookieForRemove1, cookieForRemove2]
    - cookieForRemove1
    - cookieForRemove2
  cookies:
    - !com.fakerest.bean.Cookie
      path: path1
      name: cookie1
      value: value1
      maxAge: -1
      secure: false
    - !com.fakerest.bean.Cookie
      name: cookie2
      value: value2
      secure: true
conditions:
  condition: {$and: [{ip: '127.0.0.1'}, {cookie: {'cook1": $exists}}]}
  condition: equal(ip, "127.0.0.1") and exists(cookie("cook1"))